project_id           = "your-project-id"
region              = "us-central1"
zone                = "us-central1-a"
instance_name       = "pulumi-websocket-instance"
ssh_username        = "your-username"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
ssh_private_key_path = "~/.ssh/id_rsa"
